services:
  # Bestellservice
  bestellservice:
    build:
      context: ./src/Bestellservice
    ports:
      - "8081:80"
    environment:
      DB_HOST: mariadb
      DB_NAME: webshop_db
      DB_USER: webshop_user
      DB_PASSWORD: m321

  # Lagerservice
  lagerservice:
    build:
      context: ./src/Lagerservice
    ports:
      - "8082:80"
    environment:
      DB_HOST: mariadb
      DB_NAME: webshop_db
      DB_USER: webshop_user
      DB_PASSWORD: m321

  # Kundenservice
  kundenservice:
    build:
      context: ./src/Kundenservice
    ports:
      - "8083:80"
    environment:
      DB_HOST: mariadb
      DB_NAME: webshop_db
      DB_USER: webshop_user
      DB_PASSWORD: m321

  # MariaDB
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: m321_su
      MYSQL_DATABASE: webshop_db
      MYSQL_USER: webshop_user
      MYSQL_PASSWORD: m321
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

  # NGINX API Gateway
  nginx:
    image: nginx:alpine-slim
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bestellservice
      - lagerservice
      - kundenservice
    networks:
      - default

volumes:
  mariadb_data:
